name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ github.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '>=18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cat .npmrc
          npm install

      - name: Build
        run: npm run build